chore(e2e): header, footer and homepage tests
DeFiCh/meta.defichain.com pull request #189
Opened 2022-11-15 05:48 UTC by dwivedinalin

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*

2022-11-16 02:50 UTC, mikhail-zlochevskyi commented on .github/ISSUE_TEMPLATE/1-bug-report.md
> +name: Bug report
Why do we need that? please add .github folder to gitignore file

2022-11-16 02:50 UTC, mikhail-zlochevskyi commented on public/models/jellyfish.gltf
> +      "min": [-0.999983012676239, -0.9999882578849792, -0.9999999403953552],
Why do we changed this?

2022-11-16 02:50 UTC, mikhail-zlochevskyi commented on tailwind.config.js
> +        "2.5xl": "1440px",
why do we replacing all the braces?

2022-11-16 02:50 UTC, mikhail-zlochevskyi commented on tsconfig.json
> +    "lib": ["dom", "dom.iterable", "esnext"],
why do we applying new lint rules?

2022-11-16 02:50 UTC, mikhail-zlochevskyi commented on src/styles/globals.css
> +    background-image: linear-gradient(
why do we updating css files?

2022-11-16 02:50 UTC, mikhail-zlochevskyi commented on cypress/e2e/components/header.spec.ts
> +];
please move it to fixtures

2022-11-16 02:50 UTC, mikhail-zlochevskyi commented on cypress/e2e/components/footer.spec.ts
> +  {
please move all the test data to separate folder, fixtures for examples

2022-11-16 03:17 UTC, thedoublejay commented on .github/ISSUE_TEMPLATE/1-bug-report.md
> +name: Bug report
no don't do that haha

2022-11-16 06:55 UTC, dwivedinalin commented on public/models/jellyfish.gltf
> +      "min": [-0.999983012676239, -0.9999882578849792, -0.9999999403953552],
As discussed it's expected

2022-11-16 06:55 UTC, dwivedinalin commented on tailwind.config.js
> +        "2.5xl": "1440px",
As discussed it's expected

2022-11-16 06:55 UTC, dwivedinalin commented on tsconfig.json
> +    "lib": ["dom", "dom.iterable", "esnext"],
As discussed it's expected

2022-11-16 06:55 UTC, dwivedinalin commented on src/styles/globals.css
> +    background-image: linear-gradient(
As discussed it's expected

2022-11-17 11:00 UTC, dwivedinalin commented on cypress/e2e/components/footer.spec.ts
> +  {
done

2022-11-17 11:00 UTC, dwivedinalin commented on cypress/e2e/components/header.spec.ts
> +];
done

2022-11-21 03:14 UTC, mikhail-zlochevskyi commented on cypress/e2e/components/footer.spec.ts
> +  {
test data haven't been moved yet, please move to `fixtures` folder

2022-11-21 03:16 UTC, thedoublejay requested changes

2022-11-21 03:16 UTC, thedoublejay commented on cypress/e2e/components/footer.spec.ts
> +      cy.viewport("iphone-x");
Can you put this inside the before? Since there's only one test, we don't need a separate beforeEach

2022-11-21 03:16 UTC, thedoublejay commented on cypress/e2e/components/footer.spec.ts
> +      cy.get(".hidden").invoke("show");
What is this for?

2022-11-21 03:16 UTC, thedoublejay commented on cypress/e2e/components/footer.spec.ts
> +    beforeEach(() => {
Same here, just put it on before

2022-11-21 03:16 UTC, thedoublejay commented on cypress/e2e/components/footer.spec.ts
> +      cy.findByTestId("id-Developers")
Are we testing the same on different viewports? We can create a command for it

2022-11-21 03:16 UTC, thedoublejay commented on cypress/e2e/specs/homepage.spec.ts
> +const dmc_descr =
For all consts, just camelCase. Don't use underscores

2022-11-21 03:16 UTC, thedoublejay commented on cypress/e2e/specs/homepage.spec.ts
> +      cy.get("div.flex > div.flex > span.mb-8.font-bold").should("be.visible");
What test id is this?

2022-11-21 03:16 UTC, thedoublejay commented on cypress/e2e/specs/homepage.spec.ts
> +      cy.get("div.flex > div.flex > span.mb-8.font-bold").should("be.visible");
Same here

2022-11-21 03:16 UTC, thedoublejay commented on cypress/e2e/specs/homepage.spec.ts
> +    it("should verify header", function () {
Same with the footer, let's combine repetitive tests on a command

2022-11-21 03:16 UTC, thedoublejay commented on cypress/fixtures/headerdata.ts
> +export const ul_Developer_List = [
rename this into header

2022-11-21 03:16 UTC, thedoublejay commented on cypress/fixtures/headerdata.ts
> +export const ul_Ecosystem_List = [
for lists, don't use "ul" or "nav". Just name it with proper naming, like "ecosystemList" or "communityList"

2022-11-21 03:16 UTC, thedoublejay commented on src/components/home/Footer.tsx
> +          data-testid="dmc-footer1"
why is it named dmc-footer1? Is there a dmc-footer2? If it's web/mobile, then just name it dmc-footer-web, dmc-footer-mobile

2022-11-21 03:16 UTC, thedoublejay commented on src/components/home/Footer.tsx
> +      data-testid={`id-${label}`}
Instead of using `id`, give it a more specific naming. Like `footer-community-Linkedin` for example. Don't use too generic naming

2022-11-21 03:25 UTC, dwivedinalin commented on cypress/e2e/specs/homepage.spec.ts
> +const dmc_descr =
Done

2022-11-21 03:34 UTC, dwivedinalin commented on cypress/e2e/components/footer.spec.ts
> +      cy.viewport("iphone-x");
Done

2022-11-21 03:34 UTC, dwivedinalin commented on cypress/e2e/components/footer.spec.ts
> +    beforeEach(() => {
Done

2022-11-21 03:40 UTC, dwivedinalin commented on cypress/fixtures/headerdata.ts
> +export const ul_Developer_List = [
Done

2022-11-21 03:40 UTC, dwivedinalin commented on cypress/fixtures/headerdata.ts
> +export const ul_Ecosystem_List = [
Done

2022-11-21 04:15 UTC, dwivedinalin commented on cypress/e2e/components/footer.spec.ts
> +      cy.get(".hidden").invoke("show");
Earlier faced an issue with the element as hidden hence added it. Now since working removed it.

2022-11-21 04:30 UTC, dwivedinalin commented on src/components/home/Footer.tsx
> +          data-testid="dmc-footer1"
assumed for mobile and web would be diff but it's common hence removed numeric

2022-11-21 05:22 UTC, dwivedinalin commented on cypress/e2e/components/footer.spec.ts
> +      cy.findByTestId("id-Developers")
Yes testing same on different view ports created commands for footer elements and links

2022-11-21 06:17 UTC, dwivedinalin commented on src/components/home/Footer.tsx
> +      data-testid={`id-${label}`}
replaced id with footerlink

2022-11-21 06:20 UTC, dwivedinalin commented on cypress/e2e/specs/homepage.spec.ts
> +    it("should verify header", function () {
for responsive iphone and ipad it's same converted it into command and for web it is different

2022-11-21 06:26 UTC, dwivedinalin commented on cypress/e2e/specs/homepage.spec.ts
> +      cy.get("div.flex > div.flex > span.mb-8.font-bold").should("be.visible");
It was CSS was added to test as testid weren't available

2022-11-22 04:28 UTC, mikhail-zlochevskyi approved these changes

2022-11-22 05:47 UTC, thedoublejay requested changes

2022-11-22 05:47 UTC, thedoublejay commented on cypress/e2e/components/header.spec.ts
> +
Need to move this all to before

2022-11-22 05:47 UTC, thedoublejay commented on cypress/e2e/components/header.spec.ts
> +      cy.visit("/");
Move all to before

2022-11-22 05:47 UTC, thedoublejay commented on cypress/e2e/components/header.spec.ts
> +    before(() => {
same

2022-11-22 05:47 UTC, thedoublejay commented on cypress/e2e/specs/homepage.spec.ts
> +      cy.visit("/");
Same

2022-11-22 05:47 UTC, thedoublejay commented on cypress/e2e/specs/homepage.spec.ts
> +    before(() => {
Same

2022-11-22 05:47 UTC, thedoublejay commented on cypress/e2e/specs/homepage.spec.ts
> +    before(() => {
Same

2022-11-22 05:47 UTC, thedoublejay commented on next-sitemap.config.js
> +  siteUrl: process.env.SITE_URL || "https://defimetachain.org",
Can you replace this to https://meta.defichain.com/

2022-11-22 05:47 UTC, thedoublejay commented on src/components/home/NavMenu.tsx
> +      data-testid={`hid-${label}`}
what is `hid`?

2022-11-22 07:02 UTC, dwivedinalin commented on next-sitemap.config.js
> +  siteUrl: process.env.SITE_URL || "https://defimetachain.org",
Synced from main prev but also updated the URL in code

2022-11-22 07:09 UTC, dwivedinalin commented on src/components/home/NavMenu.tsx
> +      data-testid={`hid-${label}`}
hid :: header id to make it unique since developer, ecosystem, community are present in header and footer changing it to {`header-${label}`}

2022-11-22 07:29 UTC, dwivedinalin commented on cypress/e2e/components/header.spec.ts
> +
Moving this to before doesn't get applied to the entire flow, hence breaking the test for the header and homepage.

2022-11-22 07:29 UTC, dwivedinalin commented on cypress/e2e/components/header.spec.ts
> +      cy.visit("/");
Moving this to before doesn't get applied to the entire flow, hence breaking the test for the header and homepage.

2022-11-22 07:29 UTC, dwivedinalin commented on cypress/e2e/components/header.spec.ts
> +    before(() => {
Moving this to before doesn't get applied to the entire flow, hence breaking the test for the header and homepage.

2022-11-22 07:29 UTC, dwivedinalin commented on cypress/e2e/specs/homepage.spec.ts
> +      cy.visit("/");
Moving this to before doesn't get applied to the entire flow, hence breaking the test for the header and homepage.

2022-11-22 07:29 UTC, dwivedinalin commented on cypress/e2e/specs/homepage.spec.ts
> +    before(() => {
Moving this to before doesn't get applied to the entire flow, hence breaking the test for the header and homepage.

2022-11-22 07:30 UTC, dwivedinalin commented on cypress/e2e/specs/homepage.spec.ts
> +    before(() => {
Moving this to before doesn't get applied to the entire flow, hence breaking the test for the header and homepage.

2022-11-23 00:15 UTC, thedoublejay requested changes

2022-11-23 00:15 UTC, thedoublejay commented on cypress/e2e/components/header.spec.ts
> +
You can move it to beforeEach instead

2022-11-23 06:31 UTC, thedoublejay approved these changes

2022-11-23 06:40 UTC, dwivedinalin commented on cypress/e2e/components/header.spec.ts
> +
Connected the steps moved to beforeEach

2022-11-23 06:40 UTC, dwivedinalin commented on cypress/e2e/components/header.spec.ts
> +    before(() => {
moved to beforeEach

2022-11-23 06:40 UTC, dwivedinalin commented on cypress/e2e/specs/homepage.spec.ts
> +      cy.visit("/");
moved to beforeEach

2022-11-24 06:50 UTC, mikhail-zlochevskyi commented on cypress/e2e/components/footer.spec.ts
> +    });
just make it as one test please we don't need beforeEach here, same for other resolutions/viewports

2022-11-24 06:51 UTC, mikhail-zlochevskyi commented on cypress/e2e/components/footer.spec.ts
> +});
please have at least one empty line here, same for other tests

2022-11-24 07:01 UTC, dwivedinalin commented on cypress/e2e/components/footer.spec.ts
> +});
done

2022-11-24 07:01 UTC, dwivedinalin commented on cypress/e2e/components/footer.spec.ts
> +    });
done

2022-11-24 07:24 UTC, thedoublejay approved these changes

2022-11-24 07:24 UTC, merged